### ISSUE TITLE
Science - SCRUM - Spatial Reproducible Reporting

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#115]
# Proposed Change/Activity

Proposed approach for a new era in Reproducible Reporting. We are proposing the use of SCRUM methodology to carry out work goals shared by MRP, MSP, and MCT to expand its functionality, maximizing our ability to work together across different teams/section/programs/Divisions. Below is the framework provided in the [SCRUM book](https://www.amazon.ca/Scrum-Doing-Twice-Work-Half/dp/038534645X) and in [Adrian's presentation](https://086gc.sharepoint.com/:p:/s/MaritimesSpatialPlanning-MAROpenDataLogistics/Ec7TCQGu46ZKgnbzK2ew24UBN-S9p-aCt1wUUxwKrO33uQ), with some additional notes for our proposed implementation.

# Why is this important

The Science Branch within DFO spans a range of diverse research topics and operations yet is overwhelmed by many of the same issues related to transparent, transferable, and reproducible workflows affecting science globally. We strongly believe that developing reproducible tools, particularly those that focus on data discovery and reporting, are one of the solutions to these siloed work environments.  We are looking for advice, feedback and support from all our managers to pilot this proposed way of working together. Programs will come and go, but we believe that the capabilities of this proposed approach are enduring. We are optimistic that this approach can overcome many of the challenges described in the regional capabilities assessment as it can create more stability, redundancy and support for all of us, regardless of all the changes that we have not control over (e.g. new priorities, programs, assignments, funding limitations, acting positions, leaves). 

# Context

Using R for coding and Git for version control, we developed a tool that generates automated reports to enable data-discovery of DFO and non-DFO information within the Maritimes Region: https://publications.gc.ca/collections/collection_2022/mpo-dfo/Fs97-6-3495-eng.pdf. We focus our framework on co-creation between report users, data providers, and experts to document and identify datasets along with their caveats, uncertainties, or other disclaimers. We also proactively use this as an opportunity to increase collaboration and transparency within DFO by highlighting how reproducible methods can increase efficiency and modernize workflows. Reports currently summarize over thirty data sources, with approximately twenty Reports generated thus far. This tool has reduced time spent compiling and documenting data from weeks to several minutes, allowing more time for better science. 

# Task List

- [x] Develop a board to organize and track work: https://github.com/orgs/dfo-mar-odis/projects/2/views/12
- [x] Adrian and Kyle to [draft next steps/needs/vision for RR 3.0 linked to MSP, ER, MCT](https://086gc.sharepoint.com/:p:/r/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/_layouts/15/Doc.aspx?sourcedoc=%7B6B37D885-9AEB-4A70-AAAE-65B3880F8A85%7D&file=Reproducible%20Reporting%20Discussion_Sept22022.pptx&action=edit&mobileredirect=true)
- [x] Create a [folder](https://086gc.sharepoint.com/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FMaritimesSpatialPlanning%2DMAROpenDataLogistics%2FShared%20Documents%2FMAR%20OpenData%20Logistics%2FSCRUM%2DRR&p=true&ga=1) to organize information share by the group 
- [x] Develop a [proposed plan on how to work together](https://086gc.sharepoint.com/:w:/s/MaritimesSpatialPlanning-MAROpenDataLogistics/EenCDqWN7H5JlL3J-D4EED4B1F_OBrSO6Fo5mOXOSwG9tQ?wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1663345779881&CID=B27883BD-170E-45FB-A0A0-4EE21AF87E2C&wdLOR=cD6F8C0E5-A31D-4856-BFC8-2B7ADF8CF0D1) to execute this idea
- [ ] Chat with all of our managers to get feedback and advice for next steps
- [ ] ...
