### ISSUE TITLE
Training milestones

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#134]
### Action
Tick off items from this list as you complete them.  I pulled this out of the main training ticket so that it's a little easier to keep track of individual's progress.

### Milestones for Onboarding New Developers to RR

GitHub
- [ ] I can successfully clone the ShinyApp repo from GitHub into my machine
- [ ] I can successfully edit code, create a branch, push updates to GitHub and create a pull request

RAP Board
- [ ] I can successfully contribute to RAP board (note Quentin or Catalina have to grant access to the board & the repo)
- [ ] I am familiar with the principles of asynchronous communication 

How we work
- [ ] I have read our evergreen guide about Strategic RAP Champions https://rpubs.com/MaritimesMSP/StrategicRAPChampions (advice and suggestions are welcome!)
- [ ] I have added my name to the guide for Strategic RAP Champions: create a branch, push updates to GitHub and create a pull request 
- [ ] I attended the SCRUM workshop on December 2022

Reproducible Report
- [ ] I can successfully generate a reproducible report using the app cloned from GitHub
- [ ] I am familiar with the process of requesting a new Reproducible reporting via RAP board
- [ ] I am familiar with the [metadata spreadsheet ](https://086gc.sharepoint.com/:x:/r/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/_layouts/15/Doc.aspx?sourcedoc=%7BCC28C21B-5BBD-4E38-A9A7-D96363B806D8%7D&file=ReproducibleReporting-Data-Metadata.xlsx&action=default&mobileredirect=true) and it's relationship with the Reproducible Report
