### ISSUE TITLE
Roadmap for updating data for RR

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#137]
## Proposed activity

Develop a roadmap for updating data in Spatial RR Tool

## Why this is important

Most up-to-date information is essential in support of science advice

## Action items

- [x] to re-think this action item -- > Catalina to develop a "ticket template" with check marks that could be triggered every spring to do a pulse check to pull / update data for the Spatial Reproducible Reporting tool. Ticket may include access to a file with more specific instructions.
------------> Replaced by PowerBI tool. Jake, Brian, Catalina to think about this in the future.
- [x] Develop a file with instructions on how each data source should be updated, if this information cannot be contained in the above ticket template [here](https://086gc.sharepoint.com/:x:/r/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/_layouts/15/Doc.aspx?sourcedoc=%7BCC28C21B-5BBD-4E38-A9A7-D96363B806D8%7D&file=ReproducibleReporting-Data-Metadata.xlsx&action=default&mobileredirect=true&cid=27e0e480-78f6-4d92-9d99-819317eeabab)
- [x] Update metadata spreadsheet so order matches report
- [x] @stoyelq please check metadata spreadsheet for OBIS as it lists a IN File location that I am not sure its the right one to access data? \\dcnsbiona01a\BIODataSVC\IN\MSP\Data\NaturalResources\Species\OBIS_GBIF_iNaturalist
- [x] Row by row review of instructions on how each data source should be updated, with discussion of potential PowerBI tool 

![image](https://user-images.githubusercontent.com/21310429/204316535-877aa21f-0664-4d11-a07a-ce055f3bba35.png)

**Comment by stoyelq** [comment]
OBIS + GBIF are not dependent on that folder in the IN drive, although there does appear to be some useful information stored in the metadata.txt files recording Stephen's discussions with OBIS.  

I updated the metadata sheet, but did not pull the trigger on deleting the folder in the IN drive, but I did relabel it as _old to see if that breaks anything/

**Comment by stoyelq** [comment]
I went through the rest of the metadata sheet and started chipping away at some of the outdated columns, as well as marking columns used directly in the report.

**Comment by gomezcatalina** [comment]
Two action items remain here to be tackled. Do we still need to do row by row review? I will delete the first as the PowerBI tool may help wit this moving forward.

**Comment by stoyelq** [comment]
Given that we did the column by column review, we should be okay now? The only thing left was to talk about the trickier datasets but a lot of that also got better going through #142, so I marked that as complete.

**Comment by gomezcatalina** [comment]
Main points form meeting today: 

- Jake will schedule meeting to chat about SARA database
- Quentin will separate draft critical habitat from legal critical habitat
- Quentin will add a warning message in the MARFIS/ISDB record 
- Catalina updated PowerBI tool with tiny tweaks of the metadata
