### ISSUE TITLE
Craft/Publish RAP Technical Report

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#65]
# Proposed Change/Activity

Document snapshot of this project 

# Why is this important

Good project management practices keep everything flowing, even in a remote, asynchronous environment. If you’ve got good communication and documentation strategies, it becomes much easier to implement strong project and task management.

# Additional Context

- Title: An open, efficient, and transparent spatial reproducible reporting tool for data discovery and science advice
- Authors: Quentin Stoyel, Stephen Finnis, Catalina Gomez, Gordana Lazin, Remi Daigle, Lindsay Brager, Adrian Hamer, Charlotte Smith, David Beauchesne, Kevin Cazelles, Sean Butler

[repo](https://github.com/AtlanticR/reproducible-gully-report)

# Tasks:

- [x] 	To clean document and accept/incorporate/decline tracked changes, as needed [Stephen]
- [x] 	To transfer document to google docs (to allow Kevin/David to work on it) [Stephen]
- [x] 	To email people listed in the first page to officially invite them as co-authors, and ask them to use the google doc for their edits – with a deadline to receive comments by March 28th [Stephen]
- [x] 	Incorporate co-authors comments and new version of the workflow [Stephen]
- [x] 	Prepare record form [Catalina]
- [x] 	Send tech report and record form to reviewers- Jake Coates (CESD data manager) and Mike McMahon
- [x] 	To incorporate reviewers comments - (May) [Stephen]
- [x] Merge Jake's into main [Quentin]
- [x] Make any edits in Mike's [Catalina]
- [x] Pull the updated main into Mike's [Catalina]
- [x] Merge Mike's into main [Quentin]
- [x] @gomezcatalina to submit abstract for French translation (send email to C. MacLean) http://intra.dfo-mpo.gc.ca/tools-outils/translation-traduction-eng.html [Catalina]
- [x] 	Send Tech Report and record form signed by reviewers to Section Head and Division manager - @remi-daigle to sign and get signature from Tana.
- [x] Signed record form, as well as the form to request a publication number, both get sent to the Publications mailbox [DFO.Publications.MPO@DFO-MPO.GC.CA](mailto:DFO.Publications.MPO@DFO-MPO.GC.CA) 
- [x] 	Once you get publication number, update tech report, and Submit tech report with its assigned publication number to: Publications (DFO/MPO) <[DFO.Publications.MPO@DFO-MPO.GC.CA](mailto:DFO.Publications.MPO@DFO-MPO.GC.CA)>; Libraries / Bibliotheques (DFO/MPO) <[Libraries-Bibliotheques.XENT@dfo-mpo.gc.ca](mailto:Libraries-Bibliotheques.XENT@dfo-mpo.gc.ca)> 
- [x] 	Celebrate!
