### ISSUE TITLE
Remove Fish and invertebrates / Cetaceans split  :blowfish:  :whale:

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#68]
### Proposed Change/Activity

Collapse the fish and invertebrates and cetaceans sections into a single section and make the literature review components optional.  

### Why is this important
As we add more data sources that have both fish and cetaceans (aka fish, according to DFO), splitting data sources across two sections has become more awkward. 

### Additional Context
The section 73 permits is the instigating data source for this. 

### Tasks
- [x] Collapse OBIS section
- [x] Update templates
- [x] Update table of contents
- [x] Update table of contents in the Shiny app?

**Comment by gomezcatalina** [comment]
Thank you for all the updates and re-arranging all sections - looks awesome :star2:
